# Generated by Django 3.2.7 on 2021-10-14 12:44

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True, verbose_name='дата создания товара')),
                ('recipient', models.CharField(max_length=100, verbose_name='получатель Ф.И.О')),
                ('name', models.CharField(max_length=100, verbose_name='наименование товара')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='общая цена')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='вес')),
                ('store', models.CharField(max_length=50, verbose_name='страна склада')),
                ('track', models.CharField(max_length=18, unique=True, verbose_name='трек номер')),
                ('status', models.PositiveIntegerField(choices=[(1, 'В процессе'), (2, 'Сортировка'), (3, 'Обработан'), (4, 'Выдан'), (5, 'В пути'), (6, 'В поиске'), (7, 'На складе'), (8, 'На складе в KG'), (9, 'Незарегистрированный заказ')], default=9, verbose_name='статус')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='удален')),
                ('type', models.CharField(max_length=50, verbose_name='вид товара')),
                ('site', models.URLField(verbose_name='веб-сайт')),
                ('comment', models.TextField(blank=True, max_length=324, null=True, verbose_name='коментарии')),
                ('is_bought_self', models.BooleanField(default=True, verbose_name='товар куплен клиентом')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to=settings.AUTH_USER_MODEL, verbose_name='аккаунт заказчика')),
            ],
            options={
                'verbose_name': 'посылка',
                'verbose_name_plural': 'посылки',
                'db_table': 'parcels',
            },
        ),
    ]
