# Generated by Django 3.2.7 on 2021-10-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('comment', models.CharField(blank=True, max_length=324, null=True, verbose_name='Коментарий')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
