# Generated by Django 3.2.7 on 2021-10-10 10:05

from django.db import migrations, models
import django.db.models.deletion
import sections.media_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('video', models.URLField(verbose_name='видео')),
            ],
            options={
                'verbose_name': 'информация о нас',
                'verbose_name_plural': 'информация о нас',
                'db_table': 'about_us',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название категории новостей')),
                ('slug', models.SlugField(max_length=60, verbose_name='поле slug')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название страны')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='FaqBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'FAQ блок',
                'verbose_name_plural': 'FAQ блоки',
                'db_table': 'faq_block',
            },
        ),
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'как это работает',
                'verbose_name_plural': 'как это работает',
                'db_table': 'how_it_works',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('comment', models.CharField(blank=True, max_length=324, null=True, verbose_name='Коментарий')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('url', models.URLField(verbose_name='url')),
                ('image', models.ImageField(upload_to=sections.media_path.shop_image, verbose_name='фотография')),
                ('icon', models.ImageField(unique=True, upload_to=sections.media_path.shop_icon, verbose_name='иконка')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='sections.country', verbose_name='страна')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'db_table': 'shop',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('image', models.ImageField(upload_to=sections.media_path.news_image, verbose_name='фотография')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='дата и время')),
                ('description', models.TextField(verbose_name='описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='sections.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'новости',
                'verbose_name_plural': 'новости',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='ImagesHowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sections.media_path.how_it_work_image, verbose_name='фотография')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sections.howitworks', verbose_name='как это работает')),
            ],
            options={
                'verbose_name': 'фотография HowItWorks',
                'verbose_name_plural': 'фотографии HowItWorks',
                'db_table': 'images_how_it_works',
            },
        ),
        migrations.CreateModel(
            name='ImagesAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sections.media_path.about_us_image, verbose_name='фотография')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sections.aboutusinformation', verbose_name='о нас')),
            ],
            options={
                'verbose_name': 'фотография ABOUT_US',
                'verbose_name_plural': 'фотографии ABOUT_US',
                'db_table': 'images_about_us',
            },
        ),
        migrations.CreateModel(
            name='FaqSubBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('parent_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_blocks', to='sections.faqblock', verbose_name='родительский блок')),
            ],
            options={
                'verbose_name': 'FAQ подблок',
                'verbose_name_plural': 'FAQ подблоки',
                'db_table': 'faq_sub_block',
            },
        ),
    ]
