# Generated by Django 3.2.7 on 2021-10-29 06:15

from django.db import migrations, models
import sections.media_path


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sections.media_path.partner_image, verbose_name='Логотип партнёра')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'db_table': 'partner',
            },
        ),
    ]
