# Generated by Django 3.2.7 on 2021-10-09 06:55

from django.db import migrations, models
import django.db.models.deletion
import sections.media_path


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_country_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название категории новостей')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('image', models.ImageField(upload_to=sections.media_path.news_image, verbose_name='фотография')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='дата и время')),
                ('description', models.TextField(verbose_name='описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='sections.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'новости',
                'verbose_name_plural': 'новости',
            },
        ),
    ]
