# Generated by Django 3.2.7 on 2021-10-09 12:30

from django.db import migrations, models
import django.db.models.deletion
import sections.media_path


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_category_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('video', models.URLField(verbose_name='видео')),
            ],
            options={
                'verbose_name': 'информация о нас',
            },
        ),
        migrations.CreateModel(
            name='ImagesAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sections.media_path.about_us_image, verbose_name='фотография')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sections.aboutusinformation', verbose_name='о нас')),
            ],
            options={
                'verbose_name': 'фотография',
                'verbose_name_plural': 'фотографии',
            },
        ),
    ]
