# Generated by Django 3.2.7 on 2021-10-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Страна склада')),
                ('city', models.CharField(max_length=50, verbose_name='город')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес склада')),
                ('recipient', models.CharField(max_length=100, verbose_name='получатель')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='штат')),
                ('postcode', models.CharField(max_length=50, verbose_name='почтовый код')),
                ('phone', models.CharField(max_length=50, verbose_name='телефон')),
            ],
            options={
                'verbose_name': 'склад главной страницы',
                'verbose_name_plural': 'склады главных страниц',
                'db_table': 'index_store',
            },
        ),
    ]
