# Generated by Django 3.2.7 on 2021-10-09 13:28

from django.db import migrations, models
import django.db.models.deletion
import sections.media_path


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_aboutusinformation_imagesaboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'как это работает',
                'verbose_name_plural': 'как это работает',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutusinformation',
            options={'verbose_name': 'информация о нас', 'verbose_name_plural': 'информация о нас'},
        ),
        migrations.AlterModelOptions(
            name='imagesaboutus',
            options={'verbose_name': 'фотография ABOUT_US', 'verbose_name_plural': 'фотографии ABOUT_US'},
        ),
        migrations.CreateModel(
            name='ImagesHowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sections.media_path.about_us_image, verbose_name='фотография')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sections.howitworks', verbose_name='как это работает')),
            ],
            options={
                'verbose_name': 'фотография HowItWorks',
                'verbose_name_plural': 'фотографии HowItWorks',
            },
        ),
    ]
