# Generated by Django 3.2.7 on 2021-10-29 08:53

from django.db import migrations, models
import sections.media_path


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_indexstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexstore',
            name='image',
            field=models.ImageField(default=0, upload_to=sections.media_path.index_store_image, verbose_name='фотография'),
            preserve_default=False,
        ),
    ]
