# Generated by Django 3.2.7 on 2021-10-09 14:05

from django.db import migrations, models
import django.db.models.deletion
import sections.media_path


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_auto_20211009_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'FAQ блок',
                'verbose_name_plural': 'FAQ блоки',
            },
        ),
        migrations.AlterField(
            model_name='imageshowitworks',
            name='image',
            field=models.ImageField(upload_to=sections.media_path.how_it_work_image, verbose_name='фотография'),
        ),
        migrations.CreateModel(
            name='FaqSubBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('parent_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_blocks', to='sections.faqblock', verbose_name='родительский блок')),
            ],
            options={
                'verbose_name': 'FAQ подблок',
                'verbose_name_plural': 'FAQ подблоки',
            },
        ),
    ]
